feat: Add `diff` script to easily compare against AWS
The `cdk diff` command will compare a CDK stack against one running in AWS.

By default, `cdk` will use the `id` argument as the AWS stack name.
That is, by default `cdk` will try to compare against the AWS stack "Amiable".

This change creates a script that will read the stack name from an envvar instead, wrapping it all up in a new script for ease.
You can run `./script/diff` to compare against the CODE stack in AWS, or `./script/diff --prod` to compare against the PROD stack in AWS.

The script will also check your credentials as `cdk` seems to just hang if your credentials are invalid.

diff --git a/cdk/script/diff b/cdk/script/diff
--- a/cdk/script/diff
+++ b/cdk/script/diff
@@ -2,22 +2,31 @@
 
 set -e
 
-APP=$1
-STACK=$2
-TEMPLATE_PATH=$3
+STACK_NAME=amiable-gucdk-CODE
+PROFILE=deployTools
 
-DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-ROOT_DIR="${DIR}/.."
-OUTPUT_DIR="${ROOT_DIR}/cdk.out"
+for arg in "$@"; do
+  if [ "$arg" == "--prod" ]; then
+    STACK_NAME=amiable-gucdk-PROD
+    shift
+  fi
+done
 
+checkCredentials() {
+  STATUS=$(aws sts get-caller-identity --profile ${PROFILE} 2>&1 || true)
 
-if [[ -z $APP ]]; then
-  echo -e "\033[31mPass the app you'd like to generate a diff"
-  echo -e "$0 <app> <stack> <template>\033[0m"
-  echo -e "e.g. $0 amiable Amiable ../cloudformation/amiable.yaml \033[0m"
-  exit 1
-fi
+  if [[ ${STATUS} =~ (ExpiredToken) ]]; then
+    echo "Credentials for profile '${PROFILE}' have expired. Fetch new credentials."
+    exit 1
+  elif [[ ${STATUS} =~ ("could not be found") ]]; then
+    echo "Credentials for profile '${PROFILE}' are missing. Fetch credentials."
+    exit 1
+  fi
+}
 
-pushd "${ROOT_DIR}" > /dev/null || exit
-yarn cdk diff --app="ts-node ${ROOT_DIR}/bin/${APP}.ts" --template="${TEMPLATE_PATH}" --path-metadata false --version-reporting false "${STACK}"
-popd > /dev/null
+checkCredentials
+
+export GU_CDK_STACK_NAME=${STACK_NAME}
+export AWS_PROFILE=${PROFILE}
+
+yarn diff
